# Generated by Django 3.1.5 on 2021-03-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_profile_displayname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='used',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
