# Generated by Django 3.1.5 on 2021-03-25 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_auto_20210324_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='category',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Reward',
        ),
        migrations.RemoveField(
            model_name='step',
            name='goal',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='Step',
        ),
    ]
